### ISSUE TITLE
Does the `bridge` service necessary at docker-compose.yml?

### ISSUE THREAD

**Issue by ArseniiPetrovich** [poanetwork/token-bridge#124]
As far as I see this service is exiting with non-failure code right after launch. It was required at the previous version of `docker-compose.yml` file and served as a launch point of `watchers` and `senders`. At the new version `watchers` and `senders` are considered as separate services, so I'm not sure if we still need the `bridge` service itself:
```
   build: .
    command: 'true'
    cpus: 0.1
    env_file: ./.env
    environment: [NODE_ENV=production]
    logging:
      driver: syslog
      options: {tag: '{{.Name}}/{{.ID}}'}
    mem_limit: 500m
    restart: on-failure
```
